SELECT NU_INSCRICAO, NU_ANO, TP_FAIXA_ETARIA, TP_SEXO, TP_ESTADO_CIVIL, TP_COR_RACA, TP_NACIONALIDADE, TP_ST_CONCLUSAO, TP_ANO_CONCLUIU, TP_ENSINO, IN_TREINEIRO, CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, CO_UF_PROVA, SG_UF_PROVA, Q001, Q002, Q003, Q004, Q005, Q006, Q007, Q008, Q009, Q010, Q011, Q012, Q013, Q014, Q015, Q016, Q017, Q018, Q019, Q020, Q021, Q022, Q023
FROM PARTICIPANTES;

-- Calcula a quantidade de participantes do ENEM 2024 entre homens e mulheres.
SELECT TP_SEXO, COUNT(*)
FROM PARTICIPANTES
GROUP BY TP_SEXO;

-- Calcula a porcentagem de participantes do ENEM 2024 entre homens e mulheres.
SELECT TP_SEXO, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PARTICIPANTES), 2) AS PERCENTUAL_SEXO
FROM PARTICIPANTES
GROUP BY TP_SEXO;

-- Calcula a quantidade de pessoas por etnia e exibe em ordem decrescente.
SELECT TP_COR_RACA, COUNT(*)
FROM PARTICIPANTES
GROUP BY TP_COR_RACA
ORDER BY COUNT(*) DESC;

-- Mostra a porcentagem de pessoas por etnia no ENEM 2024.
SELECT TP_COR_RACA, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PARTICIPANTES), 2) AS PERCENTUAL_ETNIA
FROM PARTICIPANTES
GROUP BY TP_COR_RACA
ORDER BY COUNT(*) DESC;
