SELECT "NU_SEQUENCIAL;NU_ANO;CO_ESCOLA;CO_MUNICIPIO_ESC;NO_MUNICIPIO_ESC;CO_UF_ESC;SG_UF_ESC;TP_DEPENDENCIA_ADM_ESC;TP_LOCALIZACAO_ESC;TP_SIT_FUNC_ESC;CO_MUNICIPIO_PROVA;NO_MUNICIPIO_PROVA;CO_UF_PROVA;SG_UF_PROVA;TP_PRESENCA_CN;TP_PRESENCA_CH;TP_PRESENCA_LC;TP_PRESENCA_MT;CO_PROVA_CN;CO_PROVA_CH;CO_PROVA_LC;CO_PROVA_MT;NU_NOTA_CN;NU_NOTA_CH;NU_NOTA_LC;NU_NOTA_MT;TX_RESPOSTAS_CN;TX_RESPOSTAS_CH;TX_RESPOSTAS_LC;TX_RESPOSTAS_MT;TP_LINGUA;TX_GABARITO_CN;TX_GABARITO_CH;TX_GABARITO_LC;TX_GABARITO_MT;TP_STATUS_REDACAO;NU_NOTA_COMP1;NU_NOTA_COMP2;NU_NOTA_COMP3;NU_NOTA_COMP4;NU_NOTA_COMP5;NU_NOTA_REDACAO", NU_SEQUENCIAL, NU_ANO, CO_ESCOLA, CO_MUNICIPIO_ESC, NO_MUNICIPIO_ESC, CO_UF_ESC, SG_UF_ESC, TP_DEPENDENCIA_ADM_ESC, TP_LOCALIZACAO_ESC, TP_SIT_FUNC_ESC, CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, CO_UF_PROVA, SG_UF_PROVA, TP_PRESENCA_CN, TP_PRESENCA_CH, TP_PRESENCA_LC, TP_PRESENCA_MT, CO_PROVA_CN, CO_PROVA_CH, CO_PROVA_LC, CO_PROVA_MT, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT, TX_RESPOSTAS_CN, TX_RESPOSTAS_CH, TX_RESPOSTAS_LC, TX_RESPOSTAS_MT, TP_LINGUA, TX_GABARITO_CN, TX_GABARITO_CH, TX_GABARITO_LC, TX_GABARITO_MT, TP_STATUS_REDACAO, NU_NOTA_COMP1, NU_NOTA_COMP2, NU_NOTA_COMP3, NU_NOTA_COMP4, NU_NOTA_COMP5, NU_NOTA_REDACAO
FROM RESULTADOS;

-- Análise exploratória dos microdados do ENEM 2024.
-- Objetivo: identificar distribuição de desempenho por UF e município.
-- Autor: aureusiohannes

-- Calcula a média de notas nas cinco áreas por unidade federativa. Substitua pelas iniciais da respectiva UF. 
SELECT AVG((NU_NOTA_MT + NU_NOTA_REDACAO + NU_NOTA_CN + NU_NOTA_LC + NU_NOTA_CH)/5)
FROM RESULTADOS
WHERE SG_UF_PROVA = 'UF';

-- Calcula a quantidade de pessoas por unidade federativa que tiraram mais de 700 em todas as matérias e mais de 900 na redação.
SELECT SG_UF_PROVA, COUNT(*) AS melhores_alunos
FROM RESULTADOS
WHERE NU_NOTA_MT >= 700 AND NU_NOTA_CH >= 700 AND NU_NOTA_CN >= 700 AND NU_NOTA_LC >= 700 AND NU_NOTA_REDACAO >= 900
GROUP BY SG_UF_PROVA
ORDER BY melhores_alunos DESC;

-- Calcula quais municípios tiveram as maiores quantidades de pessoas que alcançaram a pontuação mínima para se inscrever no SiSU na maior parte das universidades.
SELECT NO_MUNICIPIO_PROVA, COUNT(*) AS classificados_sisu
FROM RESULTADOS
WHERE NU_NOTA_MT >= 400 AND NU_NOTA_CH >= 400 AND NU_NOTA_CN >= 400 AND NU_NOTA_LC >= 400 AND NU_NOTA_REDACAO >= 400
GROUP BY NO_MUNICIPIO_PROVA
ORDER BY classificados_sisu DESC
